spring.application.name=SampleEnterpriseProj1

spring.datasource.url=jdbc:postgresql://localhost:26257/sampledb?sslmode=disable
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=root
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.CockroachDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
