spring.application.name=SampleEnterpriseProj1

spring.cassandra.contact-points=localhost
spring.cassandra.port=9042
spring.cassandra.local-datacenter=datacenter1
spring.cassandra.keyspace-name=sampledb
spring.cassandra.schema-action=create-if-not-exists
